### PR TITLE
added --clean option to stacscheck

### PR DESCRIPTION
**Pull request by ofrank123**
Added a --clean option to stacscheck that will allow the user to remove .class files from their source directory.  This was added to avoid cluttering up the source folder if the user is separating their bytecode from their source files, as is the case with most build systems.  The changes have no affect if the users do not add the --clean option, and all tests are passing.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
Hi, thanks for this PR.

While it's an interesting idea, I think in it's current state it's a bit too hard-wired.. we use stacscheck for practicals in many languages (C, Haskell and Python for example), which would need a different '--clean'. Also, some students store their class files in subdirectories, which this wouldn't find.

Out of interest, what is your reason for this? Is it to make it easier to submit without class files, or is it because when you re-run tests the old class files cause problems sometimes?

**Comment by ofrank123** [comment]
I'd be happy to expand it to other languages, and make it recursively remove the files.  My reason for doing this was so that students using various build systems other than just using javac to compile could keep their source directory clean.  I was running into this problem while using gradle, but the problem would be the same for someone using Ant or Maven.

**Comment by ChrisJefferson** [comment]
Just wanted to say, I'm still talking to staff, and investigating the right way to handle this. There might not be a good "general" option, because sometimes you don't want to delete all class files, in C you need to delete binaries (but maybe not all binaries..).

When the practical has a suggested build system, we could let the practical itself say how it should be cleaned, but that still wouldn't help students using unusual build systems.

**Comment by ChrisJefferson** [comment]
Closing this old PR -- while this is an interesting idea, I could never figure out a way to do it safely and generally.

**Pull request closed without merging**
