### PR TITLE
Extra config for guessing src folder

### PR DESCRIPTION
**Pull request by gokberkkocak**
In case of multiple source folders in a submission, an extra config parameter practicalroot will be used to preferentially select the guessed basic submission. Also, hidden folders are excluded from the search.

### CODE REVIEW

**Comment by gokberkkocak** [comment]
I just remembered about this pull request. Fixed the version that it passes the tests now. I will add one test to cover the desired case. Afterwards, you can merge it if you want.

**Comment by gokberkkocak** [comment]
Okay I've added a test as well. It took some time to remember why we want to add this feature but after checking some previous practicals I remembered and added an appropriate test to cover the wanted case.

Basically the case is, most practical setters just use "src" as srcdir that it creates a confusion with multiple presence of "src" when students have extensions. It looks like this;

```
PracticalX/src
PracticalX-Ext1/src
```
This new feature allows practical runners to use another parameter called practicalroot which can be set to "PracticalX/src" to chose the folder to test when multiple options are available.

**Comment by ChrisJefferson** [comment]
Thanks for this. I'm going to keep it open, but another person is currently rearranging the code. We will merge this after that, and I'll fix it up if things get moved around.

**Comment by ChrisJefferson** [comment]
I realise this is now very old, and you might not care any more, but I was going through old PRs. Do you think this is still a useful feature? If so I'll port it up to date.

**Comment by gokberkkocak** [comment]
Honestly, I think it's not that important anymore. It was covering a very minor percentage of submissions to begin with and afaik the extension system changed now, so not relevant anymore.

**Pull request closed without merging**
